"""add is_visible and section_type_order

Revision ID: b8497a1a89eb
Revises: 0543573de5c5
Create Date: 2026-05-02 02:35:51.077918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8497a1a89eb'
down_revision: Union[str, None] = '0543573de5c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('is_visible', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('users', sa.Column('section_type_order', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'section_type_order')
    op.drop_column('sections', 'is_visible')
    # ### end Alembic commands ###
